[package]
name = "foobar"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.15.2", features = ["dynamic_linking"] }
rand = "0.9.0"

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3
